name: Build and Deploy to EC2

on:
  push:
    branches:
        - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      #- name: Init gradle wrapper
      #  run: gradle init

      #- name: Init gradle wrapper
      #  run: gradle wrapper

      # name: Change wrapper permissions
      #  run: chmod +x ./gradlew

      # Gradle Build
      - name: Build with Gradle Clean
        run: ./gradlew clean

      # Gradle Build
      - name: Build with Gradle Build
        run: ./gradlew build -x test
